# Generated by Django 4.0.2 on 2022-03-07 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='product_id',
            new_name='msg_id',
        ),
    ]
